site_name: OhtoAi - Blog
site_url: https://blog.ohtoai.top/
repo_url: https://github.com/Ohto-Ai/blog
site_description: Blog for Ohto-Ai
site_author: Ohto-Ai

theme:
  name: material
  custom_dir: overrides

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono

  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
    logo: logo

  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes 
    - toc.follow
    - toc.integrate 
    - navigation.top
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: white
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
plugins:
  - search:
      lang: 
        - en
        - zh
extra:
  generator: true

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:zhu.thatboy@gmai.com
    - icon: fontawesome/brands/bilibili 
      link: https://space.bilibili.com/36225088
    - icon: fontawesome/brands/github 
      link: https://github.com/Ohto-Ai
    - icon: fontawesome/brands/twitter 
      link: https://gitwitterthub.com/OhtoAi_OvO
    - icon: fontawesome/brands/steam 
      link: https://steamcommunity.com/id/OhtoAi-02/
copyright: >
  Copyright &copy; 2022 <a href="https://ohtoai.top/">Ohto-Ai</a> –
  <a href="#__consent">Change cookie settings</a>